config/routes.rb
Rails.application.routes.draw do
  root to: 'top#index'
  resources :posts
  #ログイン&ログアウト
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  #サインアップ
  namespace :admin do
    resources :users
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :posts do
    new do
      post :confirm, action: :confirm_new
      get :confirm, action: :new
    end
  end

  resources :testsessions, only: :create

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  acts_as_paranoid
  belongs_to :user, optional: true
  # 「optional:true」を追加しないとuser_idがnillの場合エラー => つまり、データベースにアクセスできないので、createとupdateアクションが使えない。

  validates :client_name,
            presence: true,
            length: { maximum: 30 }

  validates :email,
            presence: true,
            format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
            length: { maximum: 50 }

  validates :phone_number,
            format: { with: /\A\d{8,11}\z/ }

  validates :near_station,
            length: { maximum: 20 }

  validates :parking_address,
            presence: true,
            uniqueness: true,
            length: { maximum: 50 }

  validates :contract_company,
            length: { maximum: 20 }

  validates :cancellation_money,
            length: { maximum: 10 }

  validates :rent,
            length: { maximum: 10 }

  validates :parking_possible_number,
            length: { maximum: 10 }

  validates :parking_size,
            length: { maximum: 10 }

  validates :desired_rent,
            length: { maximum: 10 }

  validates :desired_rent,
            length: { maximum: 10 }

  validates :client_textarea,
    length: { maximum: 250 }

  validates :user_textarea,
            length: { maximum: 250 }
  scope :recent, -> { order(created_at: :desc) }
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :posts, dependent: :nullify

  validates :name,
            presence: true,
            uniqueness: true,
            length: { maximum: 30 }

  validates :email,
            presence: true,
            uniqueness: true,
            format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
            length: { maximum: 50 }

  validates :password,
            length: { minimum: 8 }
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :require_admin

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to admin_users_path(@user), notice: "ユーザー「#{@user.name}」を登録しました。"
    else
      render :new
    end
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to admin_users_path(@user), notice: "ユーザー「#{@user.name}」を更新しました。"
    else
      render :new
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_users_url, notice: "ユーザー「#{@user.name}」を削除しました。"
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :admin, :password, :password_confirmation)
  end

  def require_admin
    redirect_to new_post_url unless current_user.admin?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :current_user
  # helper_methodは使えない。なぜ？

  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_login, except: %i[new create confirm_new]
  before_action :confirm_current_user, only: %i[create confirm_new]

  def index
    @q = Post.ransack(params[:q])
    @posts = @q.result(distinct: true).page(params[:page]).recent
    @users = User.all.includes(:posts)
  end

  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html
      format.csv { send_data render_to_string, filename: "parking-#{Time.zone.now.strftime('%Y%m%d%S')}.csv" }
    end
  end

  def create
    if params[:back]
      render :new
    elsif @post.save
      PostMailer.creation_email(@post).deliver_now
      redirect_to new_post_path(@post), notice: "「#{@post.client_name}様」の査定申し込みを受け付けました。"
    else
      render :new
      # このパスに引数を設定してやらなと、post.saveがfalseでnewアクションが呼び出された時に、postインスタンスがない状態になるのでエラーが発生
    end
  end

  def new
    @post = Post.new(flash[:post])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to post_path(@post), notice: "「査定No.#{@post.id}」のステータスを更新しました。"
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path, notice: "「査定No.#{@post.id}」のステータスを削除しました。"
  end

  def confirm_new

    redirect_to new_post_path, flash: {
      post: @post,
      error_messages: @post.errors.full_messages
    } unless @post.valid?

  end

  private

  def post_params
    params.require(:post).permit(:client_name, :email, :phone_number, :near_station, :parking_address, :parking_present, :contract_company, :year_period, :month_period, :midterm_cancellation, :cancellation_period, :cancellation_money, :rent, :tax_type, :land_estate, :parking_possible_number, :parking_size, :parking_size_unit, :start_date, :end_date, :desired_rent, :client_textarea, :user_textarea)
  end

  def require_login
    redirect_to new_post_path unless current_user
  end

  def confirm_current_user # ハードコーディング、もっと簡単に書く方法ない？
    @post = if current_user
              current_user.posts.new(post_params)
            else
              Post.new(post_params)
            end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(email: session_params[:email])

    if user&.authenticate(session_params[:password])
      session[:user_id] = user.id
      redirect_to new_post_url, notice: "#{user.name}さんがログインしました。"
    else
      render :new
    end
  end

  def destroy
    reset_session
    redirect_to new_post_url, notice: 'ログアウトしました。'
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/testsessions_controller.rb
class TestsessionsController < ApplicationController
  def create
    user = User.find_by(email: 'test@example.com')
    session[:user_id] = user.id
    redirect_to new_post_url, notice: 'テストユーザさんがログインしました。'
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    render layout: nil
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/testsessions_helper.rb
module TestsessionsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/admin/users/_form.html.erb
<div class='signup-form'>
  <%= form_with(model: [ :admin, @user ], local: true) do |f| %>
    <div class="form-group">
      <%= f.label :name, 'ユーザー名' %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :email, 'メールアドレス' %>
      <%= f.text_field :email, class: 'form-control' %>
    </div>
    <div class="form-check">
      <%= f.label class: 'form-check-label' do %>
        <%= f.check_box :admin, class: 'form-check-input' %>
          <%= '管理者権限' %>
      <%end%>
    </div>
    <div class="form-group">
      <%= f.label :password, 'パスワード(8文字以上)' %>
      <%= f.password_field :password, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :password_confirmation, 'パスワード（確認）' %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
    </div>
    <div class="regist-form">
      <%= f.submit '登録する', class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/admin/users/edit.html.erb
<h2 class="mt-4" style="text-align: center;">ユーザー編集</h2>
<%= render partial: 'form', locals: { user: @user } %>

app/views/admin/users/index.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success"><%= flash[:notice] %></div>
<% end %>
<h2 class="mt-4" style="text-align: center;">ユーザーリスト</h2>
<div class="users-wrapper">
  <%= link_to 'ユーザー追加', new_admin_user_path, class: "btn btn-primary" %>
  <div class='users-list'>
    <table class="table table-hover users__table">
      <thead class="thead">
        <tr>
          <th>ID</th>
          <th>名前</th>
          <th>管理者権限</th>
          <th>メールアドレス</th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= user.id %></td>
            <td><%= user.name %></td>
            <td><%= user.admin? ? 'あり ' : 'なし '%></td>
            <td><%= user.email %></td>
            <td>
              <%= link_to '編集', edit_admin_user_path(user), class: 'btn btn-info' %>
              <%= link_to '削除', admin_user_path(user), method: :delete, data: { confirm: "本当に削除しますか？" }, class: 'btn btn-danger' %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/users/new.html.erb
<h2 class="mt-4" style="text-align: center;">ユーザー登録</h2>
<%= render partial: 'form', locals: { user: @user } %>

app/views/application/_header.html.erb
<div class="header-bar" style="font-family:'Kosugi Maru', sans-serif;">
  <button class="fas fa-bars fa-2x" id="menu-toggle"></button>
  <ul class="header-bar-list">
    <% if @current_user %>
    <li>
      <%= link_to 'ユーザーリスト', admin_users_path, class: 'btn btn-primary' %>
    </li>
    <li>
      <%= link_to 'ログアウト', logout_path, method: :delete, class: 'btn btn-primary' %>
    </li>
    <li>
      <i class="far fa-user-circle fa-2x" style="color: #75A9FF;"><span style= "font-size: 24px; font-family:'Kosugi Maru', sans-serif;"><%= @current_user.name %></span></i>
    </li>
    <% else %>
    <li><%= link_to 'かんたんログイン', testsessions_path, method: :post, class: 'btn btn-primary' %></li>
    <li><%= link_to 'ログイン', login_path, class: 'btn btn-primary' %></li>
    <% end %>
  </ul>
</div>

app/views/application/_side.html.erb
<nav class="nav-main" style="font-family: 'Roboto', sans-serif;" id="sidebar-wrapper">
  <div class="nav-main__item">
    <a class="nav-main__link" href="/">
      <div class="nav-main__label" >On Tech</div>
    </a>
  </div>
  <ul class="nav-main__nav">
    <li class="nav-main__item">
      <a class="nav-main__link" href="/posts/new">
        <i class="nav-main__icon fa-2x fas fa-home "></i>
        <p>HOME</p>
      </a>
    </li>
    <li class="nav-main__item">
    <% if @current_user %>
      <a class="nav-main__link" href="/posts">
        <i class="nav-main__icon fas fa-file-alt fa-2x"></i>
        <p>LIST</p>
      </a>
    <% end %>
    </li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InternalApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag  'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css">
    <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Kosugi+Maru&display=swap" rel="stylesheet">
  </head>
  <body>
    <div class="d-flex" id="wrapper">
      <%= render 'side' %>
      <div id="page-content-wrapper">
        <%= render 'header' %>
        <%= yield %>
      </div>

      <script>
        $("#menu-toggle").click(function(e) {
          e.preventDefault();
          $("#wrapper").toggleClass("toggled");
        });
      </script>
    </div>
  </body>
</html>

app/views/posts/index.html.erb
<% if flash[:notice] %>
  <div class="alert alert-danger"><%= flash[:notice] %></div>
<% end %>
<h2 class="mt-4" style="text-align: center; font-family: 'Kosugi Maru', sans-serif;">査定リスト</h2>

<div class="posts-wrapper">
<%= search_form_for @q, class: "mb-5" do |f|%>
  <ul class= "form-row" >
    <li class= "col-sm-3">
      <%= f.collection_select :user_id_eq, @users, :id, :name, { :include_blank => "社員名" }, class: "form-control" %>
    </li>
    <li class="col-sm-3">
      <%= f.select :parking_present_eq, [["有", "true"], ["無", "false"]], {:include_blank => "駐車場運営" }, {class: "form-control"} %>
    </li>
    <li >
      <%= f.submit "検索" , {class: "btn btn-primary"}%>
    </li>
  </ul>
<% end %>
  <%= paginate @posts %>
    <table style="table-layout:fixed;width:100%;", class="table table-hover boards__table">
      <thead class="thead">
        <tr>
          <th class="a">NO</th>
          <th class="b">氏名</th>
          <th class="c">メール</th>
          <th class="d">住所</th>
          <th class="e">運営</th>
          <th class="f">賃料<br>(¥/月)</th>
          <th class="g">駐車台数</th>
          <th class="h">担当者</th>
          <th class="i">特記事項<br>(顧客用)</th>
          <th class="j">特記事項<br>(社員用)</th>
        </tr>
      </thead>
      <tbody>
        <% @posts.each do |post| %>
          <tr>
            <td><%= post.id %></td>
            <td><%= link_to post.client_name, post_path(post) %></td>
            <td><%= post.email %></td>
            <td><%= post.parking_address %></td>
            <td><%= post.parking_present? ? "有" : "無" %></td>
            <td><%= post.rent %></td>
            <td><%= post.parking_possible_number %></td>
          <% if post.user.present? %>
            <td><%= post.user.name %></td>
          <% else %>
            <td>なし</td>
          <% end %>
            <td><%= post.client_textarea %></td>
            <td><%= post.user_textarea %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
</div>

app/views/posts/new.html.erb
  <!-- Page Content -->
<% if flash[:notice] %>
  <div class="alert alert-success"><%= flash[:notice] %></div>
<% end %>
<% if flash[:error_messages]  %>
  <div class="alert alert-danger">
    <ul>
      <% flash[:error_messages].each do |msg|  %>
        <li><%= msg %></li>
      <% end %>
    <ul>
  </div>
<% end %>
<body> 
  <header>
    minaos
    <p style="text-align: center; font-size: 26px;">駐車場見直し本舗</p>
  </header>
  <div class="form-wrapper">
    <div class="container">
    <%= form_with model: @post, local: true, url: confirm_new_post_path do |f| %>
      <div class="form-group">
        <%= f.label :client_name do %>
          <%= '1.氏名をご記入ください。'%>
          <span class="badge-pill badge-danger"><font size="-1">必須</font><span>
        <% end %>
        <%= f.text_field :client_name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email do %>
          <%= '2.メールアドレスをご記入ください。' %>
          <span class="badge-pill badge-danger"><font size="-1">必須</font><span>
        <% end %>
        <%= f.text_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :phone_number, '3.ご連絡先(携帯番号)をご記入ください。' %><br>
        <sp><font size="-1">※半角で入力してください。</font></sp>
        <sp><font size="-1">ハイフンは入力しないでください。</font></sp>
        <%= f.text_field :phone_number, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :near_station, '4.駐車場の最寄駅をご記入ください。' %>
        <%= f.text_field :near_station, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :parking_address do %>
          <%= '5.駐車場の住所をご記入ください。' %>
          <span class="badge-pill badge-danger"><font size="-1">必須</font><span>
        <% end %>
        <%= f.text_field :parking_address, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :parking_present, '6.現在、駐車場運営の有無をお選びください。', {class: 'form-label'} %>
        <div class="input-group mb-3" data-toggle="buttons">
          <label class="btn btn-outline-secondary active" style="width:50%">
            <%= f.radio_button :parking_present, true, {checked: true} %> 有
          </label>
          <label class="btn btn-outline-secondary" style="width:50%">
            <%= f.radio_button :parking_present, false, {} %> 無
          </label>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :contract_company, '7.契約している会社名をご記入ください。' %>
        <%= f.text_field :contract_company, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :period, '8.運営期間をご記入ください。', {class: 'form-label'} %>
        <div class="input-group mb-3">
          <%= f.select :year_period, options_for_select(0..15),  { :prompt => "選択してください" }, {class: 'custom-select'} %>
          <div class="input-group-append">
            <span class="input-group-text">年</span>
          </div>
          <%= f.select :month_period, options_for_select(0..12), { :prompt => "選択してください" }, {class: 'custom-select'} %>
          <div class="input-group-append">
            <span class="input-group-text">ヶ月</span>
          </div>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :midterm_cancellation, '9.中途解約金の有無をお選びください。', {class: 'form-label'} %>
        <div class="input-group mb-3" data-toggle="buttons">
          <label class="btn btn-outline-secondary active" style="width:50%">
            <%= f.radio_button :midterm_cancellation, true, {checked: true} %> 有
          </label>
          <label class="btn btn-outline-secondary" style="width:50%">
            <%= f.radio_button :midterm_cancellation, false, {} %> 無
          </label>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :cancellation_period, '10.解約告知期間をご記入ください。', {class: 'form-label'} %>
        <div class="input-group mb-3">
          <%= f.select :cancellation_period, options_for_select(0..12), { :prompt => "選択してください" }, {class: 'custom-select'} %>
          <div class="input-group-append">
            <span class="input-group-text">ヶ月</span>
          </div>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :cancellation_money, '11.中途解約金がある場合はご記入ください。', {class: 'form-label'} %>
        <div class="input-group mb-3">
          <div class="input-group-prepend">
            <span class="input-group-text">¥</span>
          </div>
          <%= f.text_field :cancellation_money, class: 'form-control' %>
          <div class="input-group-append">
            <span class="input-group-text">円</span>
          </div>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :rent, '12.現在の1ヶ月賃料をご記入ください。', {class: 'form-label'} %>
        <div class="input-group mb-3">
          <div class="input-group-prepend">
            <span class="input-group-text">¥</span>
          </div>
          <%= f.text_field :rent, class: 'form-control' %>
          <div class="input-group-append">
            <span class="input-group-text">円/月</span>
          </div>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :tax_type, '13.税区分をお選びください。', {class: 'form-label'} %>
        <div class="input-group mb-3">
          <%= f.select :tax_type, [["税込","税込"], ["税抜","税抜"], ["非課税","非課税"]],{ :prompt => "選択してください" }, {class: "custom-select"} %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :land_estate, '14.現在の土地の状況をお選びください。', {class: 'form-label'} %>
        <div class="input-group mb-3">
          <%= f.select :land_estate, [["更地","更地"], ["アスファルト","アスファルト"], ["砂石","砂石"], ["建物下","建物下"], ["その他(※16.備考欄にご記入ください)","その他"]], { :prompt => "選択してください" }, {class: "custom-select"} %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :parking_possible_number, '15.駐車可能な台数をご記入ください。', {class: 'form-label'} %>
        <div class="input-group mb-3">
          <%= f.text_field :parking_possible_number, class: 'form-control' %>
          <div class="input-group-append">
            <span class="input-group-text">台</span>
          </div>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :parking_size, '16.駐車場の面積をご記入ください。', {class: 'form-label'} %>
        <div class="input-group mb-3" >
          <%= f.text_field :parking_size, class:"form-control", style:"width:85%" %>
          <%= f.select :parking_size_unit, [["平米","平米"], ["坪","坪"]], {:prompt => "-"} , class:"input-group-text", style:"width:15%" %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :date, '17.契約希望期間をご記入ください。', {class: 'form-label'} %>
        <div class="input-group mb-3" >
          <div class="input-group-prepend">
            <span class="input-group-text">開始</span>
          </div>
          <%= f.date_field :start_date, {class: "form-control"} %>
          <div class="input-group-prepend">
            <span class="input-group-text">終了</span>
          </div>
          <%= f.date_field :end_date, {class: "form-control"} %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :desired_rent, '18.希望の1ヶ月賃料をご記入ください。', {class: 'form-label'} %>
        <p><font size="-1">※ご希望に添えない場合がございます。</font></p>
        <div class="input-group mb-3">
          <div class="input-group-prepend">
            <span class="input-group-text">¥</span>
          </div>
          <%= f.text_field :desired_rent, {class: 'form-control'} %>
          <div class="input-group-append">
            <span class="input-group-text">円/月</span>
          </div>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :client_textarea, '19.その他特記事項（ご相談・お悩みなど）', {class: 'form-label'} %><sp><font size="-1">※250字以内</font></sp>
        <div class="input-group mb-3">
          <%= f.text_area :client_textarea, :placeholder => "今後の展望等ございましたらご記入ください。", rows: 5, class: "form-control" %>
        </div>
      </div>

      <div class="confirm-form">
        <%= f.submit "確認する", {class: "btn btn-primary"} %>
      </div>
    <% end %>
    </div>
  </div>
  <footer>
    <div class="container">
      <p style="text-align: center; font-size: 16px;">©︎On Tech</p>
    </div>
  </footer>
</body>

app/views/posts/show.html.erb
<% if flash[:notice] %>
  <div class="alert alert-primary"><%= flash[:notice] %></div>
<% end %>

<h2 class="mt-4" style="text-align: center; font-family: 'Kosugi Maru', sans-serif;">査定詳細</h2>
<div class="post-show-wrapper">
  <div class='post-show-list'>
    <div class="post-show-list-top">
      <%= link_to '一覧に戻る', posts_path, class: 'btn btn-info' %>
      <%= link_to '編集', edit_post_path(@post), class: 'btn btn-warning' %>
      <%= link_to '削除', post_path(@post), method: :delete, data: { confirm: "本当に削除しますか？" }, class: 'btn btn-danger' %>
      <%= link_to post_path(format: :csv) do %>
        <i class="fas fa-file-csv fa-2x" style="color: #75A9FF;float: right;"></i>
      <% end %>
    </div>
      <table class="table table-hover posts__table">
        <tbody>
          <tr>
            <th>氏名:</th>
            <td><%= @post.client_name %></td>
          </tr>
          <tr>
            <th>メール:</th>
            <td><%= @post.email %></td>
          </tr>
          <tr>
            <th>携帯番号:</th>
            <td><%= @post.phone_number %></td>
          </tr>
          <tr>
          <tr>
            <th>最寄駅:</th>
            <td><%= @post.near_station %></td>
          </tr>
          <tr>
            <th>住所:</th>
            <td><%= @post.parking_address %></td>
          </tr>
          <tr>
            <th>運営有無:</th>
            <td><%= @post.parking_present? ? "有" : "無" %></td>
          </tr>
          <tr>
            <th>契約会社:</th>
            <td><%= @post.contract_company %></td>
          </tr>
          <tr>
            <th>運営期間:</th>
            <td><%= @post.year_period %>年<%= @post.month_period %>ヶ月</td>
          </tr>
          <tr>
            <th>中途解約金有無:</th>
            <td><%= @post.midterm_cancellation? ? "有" : "無" %></td>
          </tr>
          <tr>
            <th>解約告知期間:</th>
            <td><%= @post.cancellation_period %>ヶ月</td>
          </tr>
          <tr>
            <th>中途解約金:</th>
            <td><%= @post.cancellation_money %>円</td>
          </tr>
          <tr>
            <th>1ヵ月賃料:</th>
            <td><%= @post.rent %>円/月</td>
          </tr>
          <tr>
            <th>税区分:</th>
            <td><%= @post.tax_type  %></td>
          </tr>
          <tr>
            <th>土地の状況:</th>
            <td><%= @post.land_estate %></td>
          </tr>
          <tr>
            <th>駐車可能な台数:</th>
            <td><%= @post.parking_possible_number %></td>
          </tr>
          <tr>
            <th>駐車場面積:</th>
            <td><%= @post.parking_size %><%= @post.parking_size_unit %></td>
          </tr>
          <tr>
            <th>利用期間:</th>
            <td>開始:<%= @post.start_date %><br>終了:<%= @post.end_date %></td>
          </tr>
          <tr>
            <th>希望の1ヶ月賃料:</th>
            <td><%= @post.desired_rent %></td>
          </tr>
          <tr>
            <th>その他特記事項<br>(顧客):</th>
            <td><%= auto_link(simple_format(h(@post.client_textarea),{}, sanitize: false, wrapper_tag: "div")) %></td>
          </tr>
          <tr>
            <th>その他特記事項<br>(社員):</th>
            <td><%= auto_link(simple_format(h(@post.user_textarea),{}, sanitize: false, wrapper_tag: "div")) %></td>
          </tr>
          <tr>
            <th>作成日時:</th>
            <td><%= @post.created_at%></td>
          </tr>
          <tr>
            <th>更新日時:</th>
            <td><%= @post.updated_at%></td>
          </tr>
        </tbody>
      </table>
  </div>
</div>